IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Quotes]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[Quotes] (
        [Id] int NOT NULL IDENTITY,
        [Subject] nvarchar(200) NOT NULL,
        [QuoteNumber] nvarchar(50) NULL,
        [Status] nvarchar(20) NULL,
        [PublicToken] uniqueidentifier NOT NULL,
        [ContactId] int NULL,
        [CompanyId] int NULL,
        [OpportunityId] int NULL,
        [QuoteTemplateId] int NULL,
        [QuoteDate] datetime2 NOT NULL,
        [ExpirationDate] datetime2 NULL,
        [SentDate] datetime2 NULL,
        [ViewedDate] datetime2 NULL,
        [AcceptedDate] datetime2 NULL,
        [DeclinedDate] datetime2 NULL,
        [Subtotal] decimal(18,2) NOT NULL,
        [DiscountPercent] decimal(5,2) NOT NULL,
        [DiscountAmount] decimal(18,2) NOT NULL,
        [TaxAmount] decimal(18,2) NOT NULL,
        [ShippingAmount] decimal(18,2) NOT NULL,
        [Total] decimal(18,2) NOT NULL,
        [Currency] nvarchar(3) NULL,
        [PaymentTerms] nvarchar(50) NULL,
        [TermsAndConditions] nvarchar(max) NULL,
        [Notes] nvarchar(max) NULL,
        [RecipientName] nvarchar(200) NULL,
        [RecipientEmail] nvarchar(255) NULL,
        [RecipientAddress] nvarchar(500) NULL,
        [ViewCount] int NOT NULL,
        [AcceptedByName] nvarchar(max) NULL,
        [AcceptedByEmail] nvarchar(max) NULL,
        [DeclineReason] nvarchar(max) NULL,
        [Version] int NOT NULL,
        [ParentQuoteId] int NULL,
        [OwnerId] int NULL,
        [CreatedAt] datetime2 NOT NULL,
        [LastModifiedAt] datetime2 NOT NULL,
        CONSTRAINT [PK_Quotes] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_Quotes_Contacts_ContactId] FOREIGN KEY ([ContactId]) REFERENCES [dbo].[Contacts] ([Id]),
        CONSTRAINT [FK_Quotes_Companies_CompanyId] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Companies] ([Id]),
        CONSTRAINT [FK_Quotes_Opportunities_OpportunityId] FOREIGN KEY ([OpportunityId]) REFERENCES [dbo].[Opportunities] ([Id])
    );
END;

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QuoteLineItems]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[QuoteLineItems] (
        [Id] int NOT NULL IDENTITY,
        [QuoteId] int NOT NULL,
        [ProductId] int NULL,
        [Name] nvarchar(200) NOT NULL,
        [SKU] nvarchar(50) NULL,
        [Description] nvarchar(max) NULL,
        [Quantity] decimal(18,4) NOT NULL,
        [UnitOfMeasure] nvarchar(20) NOT NULL,
        [UnitPrice] decimal(18,2) NOT NULL,
        [Cost] decimal(18,2) NOT NULL,
        [DiscountPercent] decimal(5,2) NOT NULL,
        [DiscountAmount] decimal(18,2) NOT NULL,
        [IsTaxable] bit NOT NULL,
        [TaxRate] decimal(5,2) NOT NULL,
        [TaxAmount] decimal(18,2) NOT NULL,
        [LineTotal] decimal(18,2) NOT NULL,
        [LineTotalWithTax] decimal(18,2) NOT NULL,
        [SortOrder] int NOT NULL,
        [GroupName] nvarchar(100) NULL,
        [Notes] nvarchar(max) NULL,
        [CreatedAt] datetime2 NOT NULL,
        [LastModifiedAt] datetime2 NOT NULL,
        CONSTRAINT [PK_QuoteLineItems] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_QuoteLineItems_Quotes_QuoteId] FOREIGN KEY ([QuoteId]) REFERENCES [dbo].[Quotes] ([Id]) ON DELETE CASCADE,
        CONSTRAINT [FK_QuoteLineItems_Products_ProductId] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Products] ([Id])
    );
END;
